require('mini.icons').setup()

require('mini.pairs').setup()
require('mini.statusline').setup()
require('mini.tabline').setup()

require('plugins.mini.ai')
require('plugins.mini.bracketed')
require('plugins.mini.bufremove')
require('plugins.mini.clue')
require('plugins.mini.comment')
require('plugins.mini.diff')
require('plugins.mini.git')
require('plugins.mini.identscope')
require('plugins.mini.surround')
